SELECT * FROM USER_TABLES;

CREATE TABLE GENIE(
   GNUM INT PRIMARY KEY,
   TITLE VARCHAR(200) NOT NULL,
   ARTIST VARCHAR(200) NOT NULL,
   ALBUM VARCHAR(200) NOT NULL,
   VIEWNUM INT NOT NULL
);

CREATE TABLE MEMBER(
   MNUM INT PRIMARY KEY,
   MID VARCHAR(200) NOT NULL,
   MPW VARCHAR(200) NOT NULL,
   MNAME VARCHAR(200) NOT NULL
);

CREATE TABLE MYPAGE( 
   MYNUM INT PRIMARY KEY,
	GNUM INT NOT NULL,
   MEMBERNUM INT NOT NULL
   );
   

SELECT * FROM USER_TABLES;
DROP TABLE GENIE;
DROP TABLE MEMBER;
DROP TABLE MYPAGE;
SELECT * FROM GENIE;
SELECT * FROM MEMBER;
SELECT * FROM MYPAGE;

INSERT INTO MYPAGE VALUES((SELECT NVL(MAX(MYNUM),0)+1 FROM MYPAGE), 40, 1111)
INSERT INTO MEMBER VALUES((SELECT NVL(MAX(MNUM),0)+1 FROM MEMBER), '1111', '1111', '관리자');